### ISSUE TITLE
How could I get the paper？

### ISSUE THREAD

**Issue by SoHardToMakeAName** [Yang-Liu1082/InvDN#1]
Hi, I am interested in your paper's title and I wonder when you would release the full paper. Besides, the image link of network architecture in your readme has failed, so I cannot get a brief knowledge about your work.

Thanks in advance.

**Comment by Yang-Liu1082** [comment]
Thank you very much for your interest in our work. I will update that this evening.

Best regards,
Yang

Sent from my iPhone

On Apr 21, 2021, at 7:36 PM, SoHardToMakeAName ***@***.***> wrote:

﻿

Hi, I am interested in your paper's title and I wonder when you would release the full paper. Besides, the image link of network architecture in your readme has failed, so I cannot get a brief knowledge about your work.

Thanks in advance.

**Comment by Yang-Liu1082** [comment]
We have uploaded the pre-print paper on Arxiv (https://arxiv.org/abs/2104.10546). We have also fixed the broken links to the images.
