### ISSUE TITLE
error in running the code

### ISSUE THREAD

**Issue by llmpass** [Yang-Liu1082/InvDN#10]
Hi,

I got 

NameError: name '\___file\___' is not defined when running through

opt['path']['root'] = osp.abspath(osp.join(\___file\___, osp.pardir, osp.pardir, osp.pardir))

at codes/options/options.py.

Any suggestions?

yours,
Luming

**Comment by 0xvjay** [comment]
try this might be helpfull

os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))

**Comment by llmpass** [comment]
> try this might be helpfull
> 
> os.path.abspath(os.path.join(os.path.dirname(**file**), os.path.pardir))

but this file is still not defined, right?

**Comment by Yang-Liu1082** [comment]
'__file__' is the directory of the option.py file. How about trying these solutions? https://stackoverflow.com/questions/16771894/python-nameerror-global-name-file-is-not-defined

**Comment by llmpass** [comment]
> '**file**' is the directory of the option.py file. How about trying these solutions? https://stackoverflow.com/questions/16771894/python-nameerror-global-name-file-is-not-defined

Thank you very much!
