### ISSUE TITLE
How to set the training folders (format)

### ISSUE THREAD

**Issue by llmpass** [Yang-Liu1082/InvDN#11]
In the yaml file, 2 folders have to be set:

    dataroot_GT: '' # path to training Clean images
    dataroot_Noisy: '' # path to training Noisy images
    
  Show I put original SIDD GT and noisy png files into these folders or show I run your crop_sidd.py to create a large number of cropped images?
  In addition, what should be the file names in those folders?

**Comment by Yang-Liu1082** [comment]
Both put the original SIDD GT/Noisy images and Crop your own patches are OK here. We will randomly crop patches in our dataset. Cropping patches as input is just to speed up the loading of data.

**Comment by llmpass** [comment]
> Both put the original SIDD GT/Noisy images and Crop your own patches are OK here. We will randomly crop patches in our dataset. Cropping patches as input is just to speed up the loading of data.

Thank you!
