### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by cskunqin** [Yang-Liu1082/InvDN#12]
I train very slowly on 2080ti, I want to know your training time and how long it takes to train 100 iter

**Comment by llmpass** [comment]
> I train very slowly on 2080ti, I want to know your training time and how long it takes to train 100 iter

On my side, I trained the model with Quadro RTX 6000, spending 48s per 100 iteration.

**Comment by YongpeiZhu** [comment]
I also train very slowly on V100. But I do not know where is the problem?

**Comment by cskunqin** [comment]
> I also train very slowly on V100. But I do not know where is the problem?

Maybe you need to put the dataset on the SSD,

**Comment by cskunqin** [comment]
> I also train very slowly on V100. But I do not know where is the problem?

Maybe you need to put the dataset in SSD

**Comment by YongpeiZhu** [comment]
> > I also train very slowly on V100. But I do not know where is the problem?
> 
> Maybe you need to put the dataset in SSD

How to do it?

**Comment by YongpeiZhu** [comment]
We have trained it in SSD. But what is the problem?

**Comment by cskunqin** [comment]
> We have trained it in SSD. But what is the problem?

我这边的训练速度大概是一小时一万步，显卡是2080ti，操作系统是Windows，patchsize128*128，batchsize为16

**Comment by sui1999** [comment]
> > 我们已经在 SSD 中对其进行了训练。但问题是什么？
> 
>
大佬，请问你代码下载后是怎么处理的，为什么我在3060TI上，两分钟只能处理八张图片，patchsize256*256，bitchsize为8

**Comment by sui1999** [comment]
> > 我们已经在 SSD 中对其进行了训练。但问题是什么？
> 
> 我这边的训练速度大概是一小时一万步，显卡是2080ti，操作系统是Windows，patchsize128*128，batchsize为16

大佬，请问你代码下载后是怎么处理的，为什么我在3060TI上，两分钟只能处理八张图片，patchsize256*256，bitchsize为8,是因为没有提前处理保存lq部分的图片吗
