### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by mengchuangji** [Yang-Liu1082/InvDN#23]
The original SIDD dataset is not a folder structure like the author's /SIDD_Medium_Srgb/GT and SIDD_Medium_Srgb/Noisy, but a SIDD_Medium_Srgb\Data\0001_001_S6_00100_00060_3200_L\*GT*.png or *NOISY*.png like this. Please tell me how the author runs the code.

**Comment by duanpanjun** [comment]
So how do you do it?
