### ISSUE TITLE
能否提供模型测试！！！！

### ISSUE THREAD

**Issue by ai-Ilike** [Yang-Liu1082/InvDN#4]
看到您的论文中，降噪的效果很好，我十分感兴趣，如果能够提供训练好的模型，我将十分感谢！

**Comment by Yang-Liu1082** [comment]
Thank you for your interest in our work. The pretrained model has been provided in 'pretrained/'.

**Comment by ai-Ilike** [comment]
感谢你的回复！不过我有遇到了新的问题，我不知道如何使用自己的测试集生成"BenchmarkNoisyBlocksSrgb.mat”。我在bing搜索了一下，看到了找到了这个链接：https://github.com/TLampr/VDNet-TF-2.0/tree/master/datasets，请问是这样生成的吗？如果不是的话，能不能把有关的资料发给我去了解一下。谢谢！

**Comment by ai-Ilike** [comment]
感谢你的回复！不过我有遇到了新的问题，我不知道如何使用自己的测试集生成"BenchmarkNoisyBlocksSrgb.mat”。我在bing搜索了一下，看到了找到了这个链接:"https://github.com/TLampr/VDNet-TF-2.0/tree/master/datasets"，请问是这样生成的吗？如果不是的话，能不能把有关的资料发给我去了解一下。谢谢！
