### ISSUE TITLE
How to make BenchmarkNoisyBlockssrgb.mat？

### ISSUE THREAD

**Issue by ai-Ilike** [Yang-Liu1082/InvDN#5]
感谢你的回复！不过我有遇到了新的问题，我不知道如何使用自己的测试集生成"BenchmarkNoisyBlocksSrgb.mat”。我在bing搜索了一下，看到了找到了这个链接:"https://github.com/TLampr/VDNet-TF-2.0/tree/master/datasets"，请问是这样生成的吗？如果不是的话，能不能把有关的资料发给我去了解一下。谢谢！

**Comment by Yang-Liu1082** [comment]
The "BenchmarkNoisyBlocksSrgb.mat” file can be downloaded from the website of SIDD https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php. 
It is "SIDD Benchmark Data".
