### ISSUE TITLE
training dataset psnr only 34.97

### ISSUE THREAD

**Issue by ai-Ilike** [Yang-Liu1082/InvDN#6]
我刚开始只使用了SIDD数据集进行训练，大概有16000张图片，psnr最终停留在32.x就不再上升了。后来又去给图片添加噪点，就是使用普通的高斯噪声，加了大概3万多继续训练，现在psnr只能达到34.97很难上去了。我想到可能是没有使用DND dataset，只是自己添加了随机的噪声才会导致这样，想请问我理解的正确吗？

原谅我不能使用英文和你交流。

**Comment by Yang-Liu1082** [comment]
Could you please add my wechat? I will talk to you to see what's going on. My wechat is: yifan1082

**Comment by leefly072** [comment]
I also saw your paper, which inspired me . I don't know if it's convenient for me to add your wechat for some questions.thanks very much.

**Comment by Yang-Liu1082** [comment]
Sure. You are welcome to add my WeChat and have a discussion.

Sent from my iPhone

On May 25, 2021, at 10:27 PM, leefly ***@***.***> wrote:

﻿

I also saw your paper, which inspired me . I don't know if it's convenient for me to add your wechat for some questions.thanks very much.

**Comment by tom666tom666** [comment]
你好，我尝试使用这个微信号加你，但发现搜不到了，可以麻烦你重新发下微信号码吗，非常感谢

**Comment by Yang-Liu1082** [comment]
你好，为了方便搜索，我把微信号改成了YangLiu_1082，抱歉没有及时更新

________________________________
